// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnNXTwukaWYG4RD-NwYqdPOHR1TFsGKe4',
    appId: '1:306747400618:web:cad9c64f205bd833d40bd3',
    messagingSenderId: '306747400618',
    projectId: 'tictok-study',
    authDomain: 'tictok-study.firebaseapp.com',
    storageBucket: 'tictok-study.appspot.com',
    measurementId: 'G-EJZYWW9YK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4GnX8nOXKdB1Bb5Dcil21SSCjbJYPpkY',
    appId: '1:306747400618:android:76f57e96e9734967d40bd3',
    messagingSenderId: '306747400618',
    projectId: 'tictok-study',
    storageBucket: 'tictok-study.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtOcMOhn3NGLWf5Ffe4V-angyY16VrgvA',
    appId: '1:306747400618:ios:fda190627d63523ad40bd3',
    messagingSenderId: '306747400618',
    projectId: 'tictok-study',
    storageBucket: 'tictok-study.appspot.com',
    iosClientId: '306747400618-pr367npdftcap35464btnaj4dkpkl2eu.apps.googleusercontent.com',
    iosBundleId: 'com.dante.tiktokClone',
  );
}
